### ISSUE TITLE
no-arrow-condition and arrow-body-style conflict

### ISSUE THREAD

**Issue by bouk** [Shopify/eslint-config-shopify#10]
@lemonmade @jufashpfy 

It seems these two rules conflict, because `[].filter((i) => i == 1)` is seen as a problem by one (no-arrow-condition doesn't allow arrow functions that have a single statement that's just a conditional) while `[].filter((i) => { return i == 1; })` is disallowed by arrow-body-style.

I'd vote we get rid of no-arrow-condition, just because I've never run into that being an issue, and not being able to write an arrow function that just has a conditional is kinda annoying

**Comment by jufashpfy** [comment]
closed https://github.com/Shopify/eslint-config-shopify/pull/11

**Comment by jufashpfy** [comment]
closed https://github.com/Shopify/eslint-config-shopify/pull/11
