### ISSUE TITLE
camelCase property_names

### ISSUE THREAD

**Issue by minasmart** [Shopify/eslint-config-shopify#15]
The [camelcase rule config](https://github.com/Shopify/eslint-config-shopify/blob/30d3470631ea72efde08fc59829d0690c5d3cb85/rules/stylistic-issues.js#L11) makes code like this invalid by default:

```javascript
$.post('https://some-shop.myshopify.com', { data: { billing_address: { ... } });
```

Property names are often driven by external concerns, so enforcing a convention on them can be difficult.

**Comment by lemonmade** [comment]
@minasmart Yeah, this is a tricky situation. We really want to force people not to use snake case in regular code, which is the most common case, so I like having the rule. Do you think it's enough to have the line comments/ file comments disabling the rule for cases where it's necessary?

**Comment by minasmart** [comment]
Line comments are OK. Another approach might be to write hashes that need to be build this way as

`{ 'billing_address': { ... } }`

That way it at least becomes obvious that I'm doing a bad thing, but there's some intent around it. The only possible problem is the [quote-props rule](http://eslint.org/docs/rules/quote-props.html). I'm not sure if you have that on or off though.

**Comment by lemonmade** [comment]
Yeah, we do have the `quote_props` rule enabled as well. I haven't seen this be an issue yet, although I don't think we've dealt with many tight Ruby-interfacing things yet. Until then, I'm going to close this (also because I am moving everything into a single repo :P)

**Comment by minasmart** [comment]
:+1:
