### ISSUE TITLE
forcing function shorthand means we can't use React.createClass()

### ISSUE THREAD

**Issue by boourns** [Shopify/eslint-config-shopify#6]
Using our eslint config with shux I ran into an issue I'm unsure how we can solve.

The following code doesn't work because the method shorthand `() => {}` creates a closure around the outer scope, so `this.props` is not defined.
```
React.createClass({
  render: () => {
  <View {...this.props} />
}
```

I need to use React.createClass in shux right now because I'm dynamically creating a new react element that containers the input component.  That's how the container works

https://github.com/boourns/shux/blob/master/src/container.js

Can I use method shorthand without acting as a closure?

**Comment by boourns** [comment]
cc @lemonmade @bouk

**Comment by lemonmade** [comment]
It's not possible to do:

```js
React.createClass({
  render() { return <View {...this.props} />; }
});
```

?

**Comment by bouk** [comment]
Can't you do this:

```javascript
import React from 'react';

function createContainer(React) {
  return (Component, stores) =>
    class extends React.Component {
      storeUpdated() {
        this.forceUpdate();
      }

      componentWillMount() {
        stores.forEach((store) => {
          store.subscribe(this.storeUpdated);
        });
      }

      componentWillUnmount() {
        stores.forEach((store) => {
          store.unsubscribe(this.storeUpdated);
        });
      }

      render() {
        return <Component {...this.props} />
      }
    }
}

export default createContainer;
```

**Comment by bouk** [comment]
Also what @lemonmade says should work too

**Comment by boourns** [comment]
thanks guys, figured JS had ways to do whatever is imaginable ;)

**Comment by bouk** [comment]
![follow_your_dreams](https://cloud.githubusercontent.com/assets/97820/10021033/ed7e5ec0-6113-11e5-9fb3-54ebe4d1e94e.gif)
